FROM registry.access.redhat.com/ubi9-minimal:latest

USER root

RUN microdnf -y install yum-utils && \
    yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo && \
    microdnf -y install tar nomad-enterprise && \
    mkdir -p /nomad/data && \
    mkdir -p /nomad/config

RUN chgrp -R 0 /usr/bin/nomad && \
    chmod -R g=u /usr/bin/nomad && \
    chgrp -R 0 /nomad && \
    chmod -R g=u /nomad && \
    usermod -a -G 0 nomad

USER nomad

ENTRYPOINT ["nomad"]
CMD ["agent", "-config=/nomad/config/server.hcl"]